eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
spring:
  application:
    name: lxx-order-consumer
    #zipkin
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        rate: 1
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 8200
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always